/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabungan;

import javax.swing.JOptionPane;

/**
 *
 * @author Ochii
 */
public class FormRekeningBaru extends javax.swing.JFrame {
    private String mode=new String("teller");
    public FormRekeningBaru() {
        initComponents();
        tPin.setVisible(false);
        lpin.setVisible(false);
        lpin1.setVisible(false);
        rSilver.setVisible(false);
        rGold.setVisible(false);
        rPlatinum.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tNoTelpon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tAlamat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tSaldo = new javax.swing.JTextField();
        bBatal = new javax.swing.JButton();
        bDaftar = new javax.swing.JButton();
        bBukaATM = new javax.swing.JCheckBox();
        lpin = new javax.swing.JLabel();
        tPin = new javax.swing.JTextField();
        lpin1 = new javax.swing.JLabel();
        rPlatinum = new javax.swing.JRadioButton();
        rSilver = new javax.swing.JRadioButton();
        rGold = new javax.swing.JRadioButton();
        lpin2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(150, 187, 124));

        jPanel1.setBackground(new java.awt.Color(150, 187, 124));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buka Rekening Baru");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nama Nasabah ");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("No Telpon");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Alamat");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Saldo awal");

        bBatal.setText("Batal");
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });

        bDaftar.setText("Daftarkan");
        bDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDaftarActionPerformed(evt);
            }
        });

        bBukaATM.setBackground(new java.awt.Color(150, 187, 124));
        bBukaATM.setText("IYA");
        bBukaATM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBukaATMActionPerformed(evt);
            }
        });

        lpin.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lpin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lpin.setText("Masukkan Pin");

        tPin.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPinActionPerformed(evt);
            }
        });

        lpin1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lpin1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lpin1.setText("Pilih Jenis Kartu ATM");

        rPlatinum.setBackground(new java.awt.Color(150, 187, 124));
        buttonGroup1.add(rPlatinum);
        rPlatinum.setText("Platinum");

        rSilver.setBackground(new java.awt.Color(150, 187, 124));
        buttonGroup1.add(rSilver);
        rSilver.setText("Silver");

        rGold.setBackground(new java.awt.Color(150, 187, 124));
        buttonGroup1.add(rGold);
        rGold.setText("Gold");

        lpin2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lpin2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lpin2.setText("Buka ATM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 98, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(rSilver)
                                        .addGap(27, 27, 27)
                                        .addComponent(rGold)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lpin1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(rPlatinum))
                            .addComponent(tAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(43, 43, 43)
                                .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lpin, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lpin2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tPin)
                                    .addComponent(tSaldo)
                                    .addComponent(tNoTelpon)
                                    .addComponent(bBukaATM, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))))
                        .addGap(107, 107, 107))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(bDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tNoTelpon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(tSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBukaATM)
                    .addComponent(lpin2))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lpin))
                .addGap(18, 18, 18)
                .addComponent(lpin1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rGold)
                    .addComponent(rPlatinum)
                    .addComponent(rSilver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBatal)
                    .addComponent(bDaftar))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDaftarActionPerformed
        try{
            Akun akun = new Akun();
            int index = akun.totalUser()-1;
            double saldo =Double.parseDouble(tSaldo.getText());
            int noRekening=Akun.akun.get(index).getNoRekening()+1;
            String nama= tNama.getText();
            String alamat=tAlamat.getText();
            String noTelpon =tNoTelpon.getText();
            System.out.println("Namm nasabah baru : "+nama+"\nno Rekening baru : "+noRekening);
            boolean cek =false;
            if(bBukaATM.isSelected()){
                String pin=tPin.getText();
                String jenis;
                if(rSilver.isSelected()){
                    jenis="silver";
                }else if(rGold.isSelected()){
                    jenis="gold";
                }else{
                    jenis="platinum";
                }
                Nasabah nasabahBaru= new Nasabah(nama,alamat,noTelpon,pin,noRekening,saldo,jenis);
                Akun.buatAkun(nasabahBaru);
                cek = Nasabah.cekRekening(noRekening);
            }else{
                Nasabah nasabahBaru=new Nasabah(nama,alamat,noTelpon,noRekening,saldo);
                Akun.buatAkun(nasabahBaru);
                cek = Nasabah.cekRekening(noRekening);
            }
            if(cek){
                JOptionPane.showMessageDialog(this,"Akun "+nama+" telah terdaftar \n dengan nomor rekening "+noRekening);
                new FormHome(mode).show();
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(this,"Maaf akun belum berhasil terdaftar\n");
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Maaf daftar harus terisi\n klik batal jika tidak ingin melanjutkan");
        }
    }//GEN-LAST:event_bDaftarActionPerformed

    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        new FormHome(mode).show();
        this.setVisible(false);
    }//GEN-LAST:event_bBatalActionPerformed

    private void bBukaATMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBukaATMActionPerformed
        if(bBukaATM.isSelected()){
            tPin.setVisible(true);
            lpin.setVisible(true);
            lpin1.setVisible(true);
            rSilver.setVisible(true);
            rGold.setVisible(true);
            rPlatinum.setVisible(true);
            
        }else{
            tPin.setVisible(false);
            lpin.setVisible(false);
            lpin1.setVisible(false);
            rSilver.setVisible(false);
            rGold.setVisible(false);
            rPlatinum.setVisible(false);
        }
    }//GEN-LAST:event_bBukaATMActionPerformed

    private void tPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRekeningBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRekeningBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRekeningBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRekeningBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRekeningBaru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBatal;
    private javax.swing.JCheckBox bBukaATM;
    private javax.swing.JButton bDaftar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lpin;
    private javax.swing.JLabel lpin1;
    private javax.swing.JLabel lpin2;
    private javax.swing.JRadioButton rGold;
    private javax.swing.JRadioButton rPlatinum;
    private javax.swing.JRadioButton rSilver;
    private javax.swing.JTextField tAlamat;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tNoTelpon;
    private javax.swing.JTextField tPin;
    private javax.swing.JTextField tSaldo;
    // End of variables declaration//GEN-END:variables
}
