
package tabungan;

import javax.swing.JOptionPane;

/**
 *
 * @author Ochii
 */
public class FormSetorTunai extends javax.swing.JFrame {
    private int noRekening=0;
    private String mode=new String();
    public FormSetorTunai() {
        initComponents();
    }
    public FormSetorTunai(int noRekening, String mode){
        initComponents();
        this.noRekening=noRekening;
        this.mode=mode;
        if(mode.equals("nasabah")){
            tNoRekening.setText(""+noRekening);
            tNoRekening.setVisible(false);
            lNoRekening.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tJumlahSetoran = new javax.swing.JTextField();
        bSetorkan = new javax.swing.JButton();
        lNoRekening = new javax.swing.JLabel();
        tNoRekening = new javax.swing.JTextField();
        bBatal = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(150, 187, 124));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Setor Tunai");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setText("Masukkan Jumlah Setoran : ");

        tJumlahSetoran.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        bSetorkan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        bSetorkan.setText("Setorkan");
        bSetorkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSetorkanActionPerformed(evt);
            }
        });

        lNoRekening.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lNoRekening.setText("No Rekening :");

        tNoRekening.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        bBatal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        bBatal.setText("Batal");
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tJumlahSetoran, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(tNoRekening, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lNoRekening, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(bBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bSetorkan))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lNoRekening, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNoRekening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(tJumlahSetoran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSetorkan)
                    .addComponent(bBatal))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSetorkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSetorkanActionPerformed
        //menerima jumlah setor tunai dari design gui
        try{
            double jumlahSetoran=Double.parseDouble(tJumlahSetoran.getText());
        //inisialisasi tempat untuk menamoung saldo
        double saldo=0;
        if(mode.equals("nasabah")){
            for(int i=0;i<Akun.akun.size();i++){
                if(Akun.akun.get(i).getNoRekening()==noRekening){
                    Akun.akun.get(i).getTabungan().simpanUang(jumlahSetoran);
                    Akun.akun.get(i).getKartuATM().simpanUang(jumlahSetoran);
                    saldo=Akun.akun.get(i).getKartuATM().getSaldo();
                    break;
                }
            }
            JOptionPane.showMessageDialog(this,"Saldo anda saat ini Rp"+(int)saldo);
            new FormHome(noRekening,mode).show();
            this.setVisible(false);
        }else{
           
            noRekening=Integer.parseInt(tNoRekening.getText());
            for(int i=0;i<Akun.akun.size();i++){
                if(Akun.akun.get(i).getNoRekening()==noRekening){
                    Akun.akun.get(i).getTabungan().simpanUang(jumlahSetoran);
                    try{
                        Akun.akun.get(i).getKartuATM().simpanUang(jumlahSetoran);
                    }catch(NullPointerException e){
                        System.out.println("maaf, akun ini tidak memiliki Kartu ATM");
                    }
                    saldo=Akun.akun.get(i).getTabungan().getSaldo();
                    break;
                }
            }
            JOptionPane.showMessageDialog(this,"Saldo nasabah saat ini Rp"+(int)saldo);
            new FormHome(mode).show();
            this.setVisible(false);
        }
        
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Maaf jumlah tidak boleh kosong\nTekan batal jika tidak ingin melanjutkan transaski");
        }
        
    }//GEN-LAST:event_bSetorkanActionPerformed

    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        if(mode.equals("nasabah")){
            new FormHome(noRekening,mode).show();
            this.setVisible(false);
        }else{
            new FormHome(mode).show();
            this.setVisible(false);
        }
    }//GEN-LAST:event_bBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSetorTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSetorTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSetorTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSetorTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSetorTunai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bBatal;
    private javax.swing.JButton bSetorkan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lNoRekening;
    private javax.swing.JTextField tJumlahSetoran;
    private javax.swing.JTextField tNoRekening;
    // End of variables declaration//GEN-END:variables
}
