/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabungan;

import javax.swing.JOptionPane;

/**
 *
 * @author Ochii
 */
public class FormPembayaran extends javax.swing.JFrame {
    private int noRekening;
    private String mode;
    public FormPembayaran() {
        initComponents();
    }
    public FormPembayaran(int noRekening, String mode) {
        initComponents();
        this.noRekening=noRekening;
        this.mode=mode;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bOVO = new javax.swing.JButton();
        bGOPAY = new javax.swing.JButton();
        bDana = new javax.swing.JButton();
        bListrik = new javax.swing.JButton();
        bLinkAJA = new javax.swing.JButton();
        bKembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(150, 187, 124));
        jPanel1.setPreferredSize(new java.awt.Dimension(683, 384));

        bOVO.setText("OVO");
        bOVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOVOActionPerformed(evt);
            }
        });

        bGOPAY.setText("GOPAY");
        bGOPAY.setPreferredSize(new java.awt.Dimension(55, 23));
        bGOPAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGOPAYActionPerformed(evt);
            }
        });

        bDana.setText("DANA");
        bDana.setPreferredSize(new java.awt.Dimension(55, 23));
        bDana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDanaActionPerformed(evt);
            }
        });

        bListrik.setText("LISTRIK");
        bListrik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListrikActionPerformed(evt);
            }
        });

        bLinkAJA.setText("LINK AJA");
        bLinkAJA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLinkAJAActionPerformed(evt);
            }
        });

        bKembali.setText("Kembali");
        bKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKembaliActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PILIH PEMBAYARAN YANG ANDA PILIH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bLinkAJA, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(bDana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bOVO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bListrik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bGOPAY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bOVO, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bGOPAY, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(bListrik, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(bDana, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(bLinkAJA, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(bKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOVOActionPerformed
        boolean cek;
        Pembayaran bayar = new Pembayaran();
        String noTelpon =JOptionPane.showInputDialog("Masukan noTelpon: ");
        double jumlah = Double.parseDouble(JOptionPane.showInputDialog("Masukkan jumlah Top UP"));
        double saldo=0;
        bayar.setJumlah(jumlah);
        cek=bayar.bayar(noRekening, noTelpon, jumlah);
        if(cek==true){
            for(int i=0; i<Akun.totalUser();i++){
                if(Akun.akun.get(i).getNoRekening()==noRekening){
                     saldo=Akun.akun.get(i).getTabungan().getSaldo();
                     break;
                }
            }
           JOptionPane.showMessageDialog(this," TOP UP OVO anda berhasil\nSisa saldo anda"+(int)saldo);
        }else{
            JOptionPane.showMessageDialog(this," TOP UP OVO gagal, saldo tidak cukup ");
        }
    }//GEN-LAST:event_bOVOActionPerformed

    private void bKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKembaliActionPerformed
       new FormHome(noRekening,mode).show();
       this.setVisible(false);
    }//GEN-LAST:event_bKembaliActionPerformed

    private void bGOPAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGOPAYActionPerformed
        boolean cek;
        Pembayaran bayar = new Pembayaran();
        String noTelpon =JOptionPane.showInputDialog("Masukan noTelpon: ");
        double jumlah = Double.parseDouble(JOptionPane.showInputDialog("Masukkan jumlah Top UP"));
        double saldo=0;
        bayar.setJumlah(jumlah);
        cek=bayar.bayar(noRekening, noTelpon, jumlah);
        if(cek==true){
            for(int i=0; i<Akun.totalUser();i++){
                if(Akun.akun.get(i).getNoRekening()==noRekening){
                     saldo=Akun.akun.get(i).getTabungan().getSaldo();
                     break;
                }
            }
           JOptionPane.showMessageDialog(this," TOP UP OVO anda berhasil\nSisa saldo anda"+(int)saldo);
        }else{
            JOptionPane.showMessageDialog(this," TOP UP OVO gagal, saldo tidak cukup ");
        }
    }//GEN-LAST:event_bGOPAYActionPerformed

    private void bDanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDanaActionPerformed
        boolean cek;
        Pembayaran bayar = new Pembayaran();
        String noTelpon =JOptionPane.showInputDialog("Masukan noTelpon: ");
        double jumlah = Double.parseDouble(JOptionPane.showInputDialog("Masukkan jumlah Top UP"));
        double saldo=0;
        bayar.setJumlah(jumlah);
        cek=bayar.bayar(noRekening, noTelpon, jumlah);
        
        if(cek==true){
            for(int i=0; i<Akun.totalUser();i++){
                if(Akun.akun.get(i).getNoRekening()==noRekening){
                     saldo=Akun.akun.get(i).getTabungan().getSaldo();
                     break;
                }
            }
           JOptionPane.showMessageDialog(this," TOP UP OVO anda berhasil\nSisa saldo anda"+(int)saldo);
        }else{
            JOptionPane.showMessageDialog(this," TOP UP OVO gagal, saldo tidak cukup ");
        }
    }//GEN-LAST:event_bDanaActionPerformed

    private void bLinkAJAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLinkAJAActionPerformed
        boolean cek;
        Pembayaran bayar = new Pembayaran();
        String noTelpon =JOptionPane.showInputDialog("Masukan noTelpon: ");
        double jumlah = Double.parseDouble(JOptionPane.showInputDialog("Masukkan jumlah Top UP"));
        double saldo=0;
        bayar.setJumlah(jumlah);
        cek=bayar.bayar(noRekening, noTelpon, jumlah);
        
        if(cek==true){
            for(int i=0; i<Akun.totalUser();i++){
                if(Akun.akun.get(i).getNoRekening()==noRekening){
                     saldo=Akun.akun.get(i).getTabungan().getSaldo();
                     break;
                }
            }
           JOptionPane.showMessageDialog(this," TOP UP OVO anda berhasil\nSisa saldo anda"+(int)saldo);
        }else{
            JOptionPane.showMessageDialog(this," TOP UP OVO gagal, saldo tidak cukup ");
        }
    }//GEN-LAST:event_bLinkAJAActionPerformed

    private void bListrikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListrikActionPerformed
        String noPelanggan =JOptionPane.showInputDialog("Masukan noPelanggan: ");
        boolean cek;
        //polimorfisme
        Pembayaran bayar = new Listrik();
        bayar.setNoPelanggan(noPelanggan);
        double jumlah=bayar.getJumlah();
        JOptionPane.showMessageDialog(this,"Tagihan listrik anda = "+jumlah);
        double saldo=0;
        cek=bayar.bayar(noRekening,noPelanggan, jumlah);
        if(cek==true){
            for(int i=0; i<Akun.totalUser();i++){
                if(Akun.akun.get(i).getNoRekening()==noRekening){
                     saldo=Akun.akun.get(i).getTabungan().getSaldo();
                     break;
                }
            }
            JOptionPane.showMessageDialog(this,"Bayar Tagihan Listrik Berhasil\n Sisa saldo anda"+(int)saldo);
        }else{
            JOptionPane.showMessageDialog(this," Bayar Tagihan Listrik anda gagal, saldo tidak cukup ");
        }
    }//GEN-LAST:event_bListrikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDana;
    private javax.swing.JButton bGOPAY;
    private javax.swing.JButton bKembali;
    private javax.swing.JButton bLinkAJA;
    private javax.swing.JButton bListrik;
    private javax.swing.JButton bOVO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
