/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabungan;

import javax.swing.JOptionPane;

/**
 *
 * @author Ochii
 */
public class FormHome extends javax.swing.JFrame {
    private int noRekening=0;
    private String mode=new String();
    /**
     * Creates new form HomeNasabah
     */
    public FormHome(){
        initComponents();
    }
    public FormHome(String mode){
        initComponents();
        //this.noPegawai=noPegawai;
        this.mode=mode;
        if(mode.equals("teller")){
            bGantiPin.setVisible(false);
            bPembayaran.setVisible(false);
        }else{
            bBukaRekening.setVisible(false);
            bBukaKartu.setVisible(false);
        }
    }
    public FormHome(int noRekening, String mode) {
        initComponents();
        this.noRekening=noRekening;
        this.mode=mode;
        if(mode.equals("nasabah")){
            bBukaRekening.setVisible(false);
            bBukaKartu.setVisible(false);
        }else{
            bGantiPin.setVisible(false);
            bPembayaran.setVisible(false);
        }
        System.out.println("No Rekening : "+noRekening);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bGantiPin = new javax.swing.JButton();
        bSetorTunai = new javax.swing.JButton();
        bTransfer = new javax.swing.JToggleButton();
        bPembayaran = new javax.swing.JButton();
        lJudul = new javax.swing.JLabel();
        bTarikTunai = new javax.swing.JButton();
        bCekSaldo1 = new javax.swing.JButton();
        bLogOut = new javax.swing.JButton();
        bBukaRekening = new javax.swing.JButton();
        bBukaKartu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(150, 187, 124));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bGantiPin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabungan/gambar/006-keyhole.png"))); // NOI18N
        bGantiPin.setText("Ganti Pin");
        bGantiPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGantiPinActionPerformed(evt);
            }
        });
        jPanel1.add(bGantiPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 200, 50));

        bSetorTunai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabungan/gambar/003-purse.png"))); // NOI18N
        bSetorTunai.setText("Setor Tunai");
        bSetorTunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSetorTunaiActionPerformed(evt);
            }
        });
        jPanel1.add(bSetorTunai, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 200, 50));

        bTransfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabungan/gambar/001-money-transfer.png"))); // NOI18N
        bTransfer.setText("Transfer");
        bTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTransferActionPerformed(evt);
            }
        });
        jPanel1.add(bTransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 200, 50));

        bPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabungan/gambar/004-wallet.png"))); // NOI18N
        bPembayaran.setText("Pembayaran");
        bPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPembayaranActionPerformed(evt);
            }
        });
        jPanel1.add(bPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 200, 50));

        lJudul.setBackground(new java.awt.Color(223, 228, 234));
        lJudul.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        lJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lJudul.setText("Selamat Datang di Aplikasi Tabunganku");
        jPanel1.add(lJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 520, 90));

        bTarikTunai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabungan/gambar/003-withdrawal.png"))); // NOI18N
        bTarikTunai.setText("Tarik Tunai");
        bTarikTunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTarikTunaiActionPerformed(evt);
            }
        });
        jPanel1.add(bTarikTunai, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 200, 50));

        bCekSaldo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabungan/gambar/004-money.png"))); // NOI18N
        bCekSaldo1.setText("Cek Saldo");
        bCekSaldo1.setMaximumSize(new java.awt.Dimension(111, 41));
        bCekSaldo1.setMinimumSize(new java.awt.Dimension(111, 41));
        bCekSaldo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCekSaldo1ActionPerformed(evt);
            }
        });
        jPanel1.add(bCekSaldo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 200, 50));

        bLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabungan/gambar/008-logout.png"))); // NOI18N
        bLogOut.setText("Log Out");
        bLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(bLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 200, 50));

        bBukaRekening.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabungan/gambar/002-customer.png"))); // NOI18N
        bBukaRekening.setText("Buka Rekening");
        bBukaRekening.setActionCommand("bBukaRekening");
        bBukaRekening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBukaRekeningActionPerformed(evt);
            }
        });
        jPanel1.add(bBukaRekening, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 200, 50));

        bBukaKartu.setText("Buat Kartu ATM");
        bBukaKartu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBukaKartuActionPerformed(evt);
            }
        });
        jPanel1.add(bBukaKartu, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 200, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGantiPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGantiPinActionPerformed
        //mengarahkan ke halaman ganti pin
        new FormGantiPin(noRekening, mode).show();
        //membuat halaman homeNasabah tidak tampak
        this.setVisible(false);
    }//GEN-LAST:event_bGantiPinActionPerformed

    private void bSetorTunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSetorTunaiActionPerformed
        //mengarahkan ke halaman setor tunai
        new FormSetorTunai(this.noRekening,this.mode).show();
        //membat halaman home Nasabah tidak tampak
        this.setVisible(false);
    }//GEN-LAST:event_bSetorTunaiActionPerformed

    private void bTarikTunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTarikTunaiActionPerformed
       new FromTarikTunai(this.noRekening,this.mode).show();
       this.setVisible(false);
    }//GEN-LAST:event_bTarikTunaiActionPerformed

    private void bTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTransferActionPerformed
        new FormTransfer(this.noRekening,this.mode).show();
        this.setVisible(false);
    }//GEN-LAST:event_bTransferActionPerformed

    private void bCekSaldo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCekSaldo1ActionPerformed
        if(mode.equals("nasabah")){
            for(int i=0;i<Akun.akun.size();i++){
                if(Akun.akun.get(i).getNoRekening()==noRekening){
                    JOptionPane.showMessageDialog(this,"Saldo anda saat ini Rp"+(int)Akun.akun.get(i).getKartuATM().getSaldo()+"");
                    break;
                }
            }
        }else{
            Akun akun = new Akun();
            noRekening = Integer.parseInt(JOptionPane.showInputDialog("Masukan noRekening : "));
            System.out.println("no Rekening : "+noRekening);
            for(int i=0;i<Akun.totalUser();i++){
                if(Akun.akun.get(i).getNoRekening()==noRekening){
                    JOptionPane.showMessageDialog(this,"Saldo "+Akun.akun.get(i).getNama()+" saat ini Rp"+(int)Akun.akun.get(i).getTabungan().getSaldo());
                    break;
                }
            }
        }
    }//GEN-LAST:event_bCekSaldo1ActionPerformed

    private void bLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogOutActionPerformed
       new FormUtama().show();
       this.setVisible(false);
       this.dispose();
    }//GEN-LAST:event_bLogOutActionPerformed

    private void bBukaRekeningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBukaRekeningActionPerformed
        new FormRekeningBaru().show();
        this.setVisible(false);
    }//GEN-LAST:event_bBukaRekeningActionPerformed

    private void bBukaKartuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBukaKartuActionPerformed
        System.out.println("Berhasil masuk");
        new FormBukaATM(mode).show();
        this.setVisible(false);
    }//GEN-LAST:event_bBukaKartuActionPerformed

    private void bPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPembayaranActionPerformed
        new FormPembayaran(noRekening,mode).show();
        this.setVisible(false);
    }//GEN-LAST:event_bPembayaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBukaKartu;
    private javax.swing.JButton bBukaRekening;
    private javax.swing.JButton bCekSaldo1;
    private javax.swing.JButton bGantiPin;
    private javax.swing.JButton bLogOut;
    private javax.swing.JButton bPembayaran;
    private javax.swing.JButton bSetorTunai;
    private javax.swing.JButton bTarikTunai;
    private javax.swing.JToggleButton bTransfer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lJudul;
    // End of variables declaration//GEN-END:variables
}
