/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabungan;

import javax.swing.JOptionPane;

/**
 *
 * @author Ochii
 */
public class FormTransfer extends javax.swing.JFrame {
    private int noRekening;
    private String mode=new String("nasabah");
    public FormTransfer() {
        initComponents();
    }
    public FormTransfer(int noRekening, String mode){
        initComponents();
        this.noRekening=noRekening;
        this.mode=mode;
        if(mode.equals("nasabah")){
            lNoRekeningAsal.setVisible(false);
            tNoRekeningAsal.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tJumlah = new javax.swing.JTextField();
        bTransfer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tNoRekeningTujuan = new javax.swing.JTextField();
        lNoRekeningAsal = new javax.swing.JLabel();
        tNoRekeningAsal = new javax.swing.JTextField();
        bBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(150, 187, 124));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Transfer");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setText("Masukkan Jumlah Transfer");

        tJumlah.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        bTransfer.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        bTransfer.setText("Transfer");
        bTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTransferActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setText("No. Rekening Tujuan");

        tNoRekeningTujuan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lNoRekeningAsal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lNoRekeningAsal.setText("No. Rekening Asal");

        tNoRekeningAsal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        bBatal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        bBatal.setText("Batal");
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lNoRekeningAsal)
                            .addComponent(tJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(tNoRekeningTujuan)
                            .addComponent(tNoRekeningAsal)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(bBatal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bTransfer))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lNoRekeningAsal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNoRekeningAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNoRekeningTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTransfer)
                    .addComponent(bBatal))
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTransferActionPerformed
        try{
        int noRekeningTujuan=Integer.parseInt(tNoRekeningTujuan.getText());
        double jumlahTransfer = Double.parseDouble(tJumlah.getText());
        boolean cek;
        if(mode.equals("nasabah")){
            for(int i=0;i<Akun.akun.size();i++){
            if(Akun.akun.get(i).getNoRekening()==noRekening){
                cek=Akun.akun.get(i).getKartuATM().transfer(noRekeningTujuan, jumlahTransfer);
                if(cek){
                    //perubahan juga terjadi di saldo tabungan
                    Akun.akun.get(i).getTabungan().setSaldo(Akun.akun.get(i).getTabungan().getSaldo()-jumlahTransfer);
                    JOptionPane.showMessageDialog(this,"Saldo anda saat ini "+(int)Akun.akun.get(i).getKartuATM().getSaldo());
                    for(int j=0;j<Akun.totalUser();j++){
                        if(Akun.akun.get(j).getNoRekening()==noRekeningTujuan){
                          JOptionPane.showMessageDialog(this,"Saldo no Rekening tujuan saat ini "+(int)Akun.akun.get(j).getTabungan().getSaldo());
                          break;
                        }
                    }
                    new FormHome(noRekening,mode).show();
                    this.setVisible(false);
                    break;
                }else{
                    JOptionPane.showMessageDialog(this,"Maaf, transaksi tidak dapat dilakukan ! \nSaldo anda saat ini "+(int)Akun.akun.get(i).getKartuATM().getSaldo()+"\n Saldo tidak cukup atau Kartu ATM anda tidak mendukung transaki ini\n Tingkatkan kartu untuk transaksi lebih baik");
                    tNoRekeningTujuan.setText("");
                    tJumlah.setText("");
                }
            }
            }  
        }else{
            noRekening=Integer.parseInt(tNoRekeningAsal.getText());
            for(int i=0;i<Akun.akun.size();i++){
                if(Akun.akun.get(i).getNoRekening()==noRekening){
                cek=Akun.akun.get(i).getTabungan().transfer(noRekeningTujuan, jumlahTransfer);
                if(cek){
                    //mencoba mengurangi saldo di kartu atm jika ada
                    try{
                        Akun.akun.get(i).getKartuATM().setSaldo(Akun.akun.get(i).getKartuATM().getSaldo()-jumlahTransfer);
                    }catch(NullPointerException e){
                        System.out.println("akun ini tidak memiliki kartu ATM");
                    }
                    JOptionPane.showMessageDialog(this,"Transfer berhasil\nSaldo nasabah saat ini "+(int)Akun.akun.get(i).getTabungan().getSaldo());
                    for(int j=0;j<Akun.totalUser();j++){
                        if(Akun.akun.get(j).getNoRekening()==noRekeningTujuan){
                          JOptionPane.showMessageDialog(this,"Saldo no Rekening tujuan saat ini "+(int)Akun.akun.get(j).getTabungan().getSaldo());
                          break;
                        }
                    }
                    new FormHome(mode).show();
                    this.setVisible(false);
                    break;
                    
                }else{
                    JOptionPane.showMessageDialog(this,"Maaf saldo nasabah tidak cukup untuk melakukan tarnsaksi ini");
                    tNoRekeningAsal.setText("");
                    tNoRekeningTujuan.setText("");
                    tJumlah.setText("");
                } 
            }
            new FormHome(mode).show();
            this.setVisible(false);
            }
        }
        }catch(NumberFormatException e ){
             JOptionPane.showMessageDialog(this,"Maaf from harus terisi\n klik batal jika tidak ingin melanjutkan");
        }
        
    }//GEN-LAST:event_bTransferActionPerformed

    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        if(mode.equals("nasabah")){
            new FormHome(noRekening,mode).show();
            this.setVisible(false);
        }else{
            new FormHome(mode).show();
            this.setVisible(false);
        }
    }//GEN-LAST:event_bBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBatal;
    private javax.swing.JButton bTransfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lNoRekeningAsal;
    private javax.swing.JTextField tJumlah;
    private javax.swing.JTextField tNoRekeningAsal;
    private javax.swing.JTextField tNoRekeningTujuan;
    // End of variables declaration//GEN-END:variables
}
