
package tabungan;
import javax.swing.JOptionPane;
/**
 *
 * @author Ochii
 */
public class FromLogin extends javax.swing.JFrame {
    private String mode=new String("nasabah");
    public FromLogin() {
        initComponents();
    }
    public FromLogin(String mode){
        initComponents();
        this.mode=mode;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        lUsername = new javax.swing.JLabel();
        lPin = new javax.swing.JLabel();
        tUsername = new javax.swing.JTextField();
        tPin = new javax.swing.JPasswordField();
        bLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(150, 187, 124));
        jPanel3.setAutoscrolls(true);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabungan/gambar/001-user.png"))); // NOI18N
        lUsername.setText("Username");
        jPanel3.add(lUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 190, 50));

        lPin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabungan/gambar/006-keyhole.png"))); // NOI18N
        lPin.setText("Pin");
        jPanel3.add(lPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 180, 50));
        jPanel3.add(tUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 180, 30));
        jPanel3.add(tPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 180, 30));

        bLogin.setBackground(new java.awt.Color(214, 239, 199));
        bLogin.setText("Login");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });
        jPanel3.add(bLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 180, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Silahkan Login");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jPanel1.setBackground(new java.awt.Color(214, 239, 199));

        jLabel2.setBackground(new java.awt.Color(214, 239, 199));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Selamat Datang di Tabunganku");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        //memindahkan ke varibale
        String name=tUsername.getText();
        String pin =tPin.getText();
        boolean cek;
        if(mode.equals("nasabah")){
            Akun akun= new Akun();
            cek =Akun.cekAkun(name,pin);
            if(cek){
             int noRekening = 0;
                for(int i=0; i< Akun.akun.size();i++){
                    if(Akun.akun.get(i).getNama().equals(name)&& Akun.akun.get(i).getKartuATM().getPin().equals(pin)){
                       noRekening = Akun.akun.get(i).getNoRekening();
                    }
                }
                  new FormHome(noRekening,mode).show();
                  this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(this,"Username atau password salah");
                tUsername.setText("");
                tPin.setText("");
            }
        }else{
            Teller pegawai = new Teller();
            cek=Teller.loginTeller(name, pin);
            if(cek){
                new FormHome(mode).show();
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(this,"Maaf Username atau password anda salah");
                tUsername.setText("");
                tPin.setText("");
            }
        }
    }//GEN-LAST:event_bLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lPin;
    private javax.swing.JLabel lUsername;
    private javax.swing.JPasswordField tPin;
    private javax.swing.JTextField tUsername;
    // End of variables declaration//GEN-END:variables
}
