
package tabungan;

import javax.swing.JOptionPane;

/**
 *
 * @author Ochii
 */
public class FromTarikTunai extends javax.swing.JFrame {
    private String mode=new String();
    private int noRekening;
    
    public FromTarikTunai() {
        initComponents();
    }
    public FromTarikTunai(int noRekening, String mode){
        initComponents();
        this.noRekening=noRekening;
        this.mode=mode;
        if(mode.equals("nasabah")){
            lNoRekening.setVisible(false);
            tNoRekening.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bAmbil = new javax.swing.JButton();
        tJumlah = new javax.swing.JTextField();
        lNoRekening = new javax.swing.JLabel();
        tNoRekening = new javax.swing.JTextField();
        bBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(150, 187, 124));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tarik Tunai");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setText("Nominal yang akan diambil");

        bAmbil.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        bAmbil.setText("Ambil");
        bAmbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAmbilActionPerformed(evt);
            }
        });

        tJumlah.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lNoRekening.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lNoRekening.setText("No Rekening");

        tNoRekening.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        bBatal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        bBatal.setText("Batal");
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(bBatal)
                            .addGap(112, 112, 112)
                            .addComponent(bAmbil))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tNoRekening, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(lNoRekening, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lNoRekening, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNoRekening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAmbil)
                    .addComponent(bBatal))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAmbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAmbilActionPerformed
        try{
        double jumlahPengambilan = Double.parseDouble(tJumlah.getText());
        double saldo;
        boolean cek;
        if(mode.equals("nasabah")){
            for(int i=0; i <Akun.akun.size(); i++){
                if(Akun.akun.get(i).getNoRekening()==noRekening){
                    cek = Akun.akun.get(i).getKartuATM().ambilUang(jumlahPengambilan);
                    saldo=Akun.akun.get(i).getKartuATM().getSaldo();
                    if(cek ==true){
                        Akun.akun.get(i).getTabungan().ambilUang(jumlahPengambilan);
                        JOptionPane.showMessageDialog(this,"Transaksi berhasil\n Saldo anda saat ini Rp"+(int)saldo);
                        new FormHome(noRekening,mode).show();
                        this.setVisible(false);
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"Maaf saldo tidak mencukupi atau jenis kartu ATM "+Akun.akun.get(i).getKartuATM().getJenis()+"anda tidak mendukung untuk melakukan tarnsaksi ini \n Saldo anda saat ini Rp"+(int)saldo+"\nTingkatkan kartu untuk membuat transaksi lebih nyaman");
                        tJumlah.setText("");
                    }
                    break;
                }
            }
        }else{
           this.noRekening=Integer.parseInt(tNoRekening.getText());
           for(int i=0; i <Akun.akun.size(); i++){
                if(Akun.akun.get(i).getNoRekening()==noRekening){
                    cek = Akun.akun.get(i).getTabungan().ambilUang(jumlahPengambilan);
                    saldo=Akun.akun.get(i).getTabungan().getSaldo();
                    if(cek ==true){
                        try{
                            Akun.akun.get(i).getKartuATM().ambilUang(jumlahPengambilan);
                        }catch(NullPointerException e){
                            System.out.println("Nasabah atas nama"+Akun.akun.get(i).getNama()+"tidak memiliki kartu ATM");
                        } 
                        JOptionPane.showMessageDialog(this,"Transaksi berhasil\n Saldo anda saat ini Rp"+(int)saldo);
                        new FormHome(mode).show();
                        this.setVisible(false);
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"Maaf saldo tidak mencukupi \n Saldo anda saat ini Rp"+(int)saldo);
                        tJumlah.setText("");
                    }
                    break;
                }
            }
        }
       }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(this,"Maaf form tidak boleh kosong\nTekan batal jika tidak ingin melanjutkan transaski");
       }
    }//GEN-LAST:event_bAmbilActionPerformed

    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        if(mode.equals("nasabah")){
            new FormHome(noRekening,mode).show();
            this.setVisible(false);
        }else{
            new FormHome(mode).show();
            this.setVisible(false);
        }
    }//GEN-LAST:event_bBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromTarikTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromTarikTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromTarikTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromTarikTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromTarikTunai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAmbil;
    private javax.swing.JButton bBatal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lNoRekening;
    private javax.swing.JTextField tJumlah;
    private javax.swing.JTextField tNoRekening;
    // End of variables declaration//GEN-END:variables
}
